import http from "node:http";
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { handleAssistant } from "./assistant-api.mjs";
const root=new URL("./dist/",import.meta.url),port=Number(process.env.PORT||4174);
const files=new Set(["communication-registration.html","communication-registration.js","communication-upi.png","career-path.html","career-path.js","programs.html","internships.html","quizzes.js","quizzes-data.js","internship-data-analytics.html","internship-ai-ml.html","internship-web-development.html","internship-business-analytics.html","internship-digital-marketing.html","internship-ui-ux.html","internship-cybersecurity.html","projects.html","career-center.html","project-retail-sales-intelligence.html","project-customer-segmentation.html","project-loan-eligibility.html","project-e-commerce-analytics.html","project-ai-resume-screening.html","career-guide-resume.html","career-guide-linkedin.html","career-guide-interviews.html","career-guide-sql-practice.html","career-guide-python-practice.html","career-guide-power-bi.html","career-guide-aptitude.html","career-guide-communication.html","career-guide-mock-interviews.html","career-guide-career-roadmaps.html","career-guide-portfolio.html","practice-form.html","practice-form.js","internship-application.html","internship-application.js","enquiry-popup.js","student-reviews.js","index.html","skills.html","training.html","about.html","contact.html","certificate-demo.html","app.js","assistant.js","styles.css","logo.jpg","favicon.svg","careers.html","program-communication-skills.html","skill.html","lesson.html","learning.js","learning-data.js","career-application.html","career-application.js","program-full-stack-development.html","program-frontend-development.html","program-backend-development.html","program-data-analyst.html","program-data-science.html","program-generative-ai.html","program-human-resource.html","program-business-analyst.html","program-artificial-intelligence.html","program-machine-learning.html"]);
http.createServer(async(req,res)=>{try{const origin="http://"+req.headers.host,url=new URL(req.url,origin);if(url.pathname.startsWith("/api/assistant")){let body="";for await(const chunk of req){body+=chunk;if(body.length>20000){res.writeHead(413);return res.end()}}const headers=new Headers(req.headers);headers.set("x-client-ip",req.socket.remoteAddress||"local");const request=new Request(url,{method:req.method,headers,...(req.method==="POST"?{body}:{})});const result=await handleAssistant(request,process.env);res.writeHead(result?.status||404,Object.fromEntries(result?.headers||[]));return res.end(result?await result.text():"Not found")}
const name=url.pathname==="/"?"index.html":url.pathname.slice(1);if(!files.has(name)){res.writeHead(404);return res.end("Not found")}const bytes=await readFile(new URL(name,root));const ext=name.split(".").at(-1);res.writeHead(200,{"Content-Type":({html:"text/html; charset=utf-8",js:"text/javascript",css:"text/css",jpg:"image/jpeg",png:"image/png",svg:"image/svg+xml"})[ext],"X-Content-Type-Options":"nosniff"});res.end(bytes)}catch{res.writeHead(500);res.end("Server error")}}).listen(port,"127.0.0.1",()=>console.log("http://127.0.0.1:"+port));

